CREATE USER IF NOT EXISTS 'SSAFY'@'localhost' IDENTIFIED BY 'SSAFY';
CREATE USER IF NOT EXISTS 'SSAFY'@'127.0.0.1' IDENTIFIED BY 'SSAFY';

GRANT ALL PRIVILEGES ON kpop_radio.* TO 'SSAFY'@'localhost';
GRANT ALL PRIVILEGES ON kpop_radio.* TO 'SSAFY'@'127.0.0.1';
FLUSH PRIVILEGES;

USE kpop_radio;
SHOW TABLES;